// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUHFtGYJmkcbvdE8e1Y1awpwuYW-1Mywc',
    appId: '1:862828171228:web:074ef00b2c1f2cd3d88919',
    messagingSenderId: '862828171228',
    projectId: 'whatsappclone-f1f60',
    authDomain: 'whatsappclone-f1f60.firebaseapp.com',
    storageBucket: 'whatsappclone-f1f60.appspot.com',
    measurementId: 'G-KLKNSD8RQ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0ROa_IgvZ2Pgx-tS6hdDSLrPJXd8652s',
    appId: '1:862828171228:android:5c1e558fac9694fdd88919',
    messagingSenderId: '862828171228',
    projectId: 'whatsappclone-f1f60',
    storageBucket: 'whatsappclone-f1f60.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCyqKIeIEel0kkhEpZUsSFv8uiiYzqkO4w',
    appId: '1:862828171228:ios:79ee5fcab9cc6a3cd88919',
    messagingSenderId: '862828171228',
    projectId: 'whatsappclone-f1f60',
    storageBucket: 'whatsappclone-f1f60.appspot.com',
    iosClientId: '862828171228-f9qa2e78r966986arkki1kerf35p73ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCyqKIeIEel0kkhEpZUsSFv8uiiYzqkO4w',
    appId: '1:862828171228:ios:79ee5fcab9cc6a3cd88919',
    messagingSenderId: '862828171228',
    projectId: 'whatsappclone-f1f60',
    storageBucket: 'whatsappclone-f1f60.appspot.com',
    iosClientId: '862828171228-f9qa2e78r966986arkki1kerf35p73ku.apps.googleusercontent.com',
    iosBundleId: 'com.example.whatsAppClone',
  );
}
